### ISSUE TITLE
Search bar searches lead to missing GitHub Pages

### ISSUE THREAD

**Issue by koenderks** [amirmasoudabdol/preferably#11]
Thanks for the package! 

I'm using this package for the `jfa` package (https://koenderks.github.io/jfa/). When I search for a term (e.g., 'citation') in the search bar, and click one of the available options (e.g., 'Authors and citation') the page it directs me to is always missing (e.g., https://koenderks.github.io/authors.html?q=citation#citation).

![image](https://user-images.githubusercontent.com/25059399/163707650-b359420a-3587-45cc-8dea-677ef8791e6c.png)

Is there a way to easily fix this? Maybe I am overlooking something. Thanks for the help!

**Comment by amirmasoudabdol** [comment]
Hey Koen! I think this might be due to your [CITATION.cff](https://github.com/koenderks/jfa/blob/development/CITATION.cff) file looking slightly different. I am not 100% sure, but I think it should just be `CITATION` without the suffix.

I don't do anything special with the citation handling, and I reckon as long as `{pkgdown}` can recognize and traverse to the citations, you should be good.

**Comment by koenderks** [comment]
I don't think that that is the problem because got this issue before I changed the CITATION.cff file (there is a regular CITATION file in `inst/CITATION`). Its also not specifically for the citation links actually, but all pages resulting from a search in the search bar. Try searching for "function" or something and clicking the resulting first link: https://koenderks.github.io/articles/v3_prior_distributions.html?q=function#using-a-prior-distribution-in-other-functions.

**Comment by amirmasoudabdol** [comment]
Ok, I noticed something else. If I search for `Prior Audit`, the search URL goes here, `https://koenderks.github.io/reference/auditPrior.html?q=prior%20a#null` and if I go the same page, the URL is this, `https://koenderks.github.io/jfa/reference/auditPrior.html`. Notice the missing `jfa` in the search URL.

So, maybe, since you are not using the default GitHub Page of your repo, you might need to set your base URL, like [this](https://github.com/amirmasoudabdol/preferably/blob/9148fc908b45702b5da6d5d5c0d6214603fb585e/_pkgdown.yml#L1). If this doesn't work, you might wanna check where your GitHub Page points too. Check the Repo Settings -> Pages -> Custom Domain. But, change the `_pkgdown.yml` first.

**Comment by koenderks** [comment]
Setting the base URL to `https://koenderks.github.io/jfa` worked, thanks for your help!

**Comment by amirmasoudabdol** [comment]
No problem! 🙂

P.S. Happy Easter! 🐣🌸🌼

**Comment by koenderks** [comment]
Happy easter to you too! 😃
